services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  Tourze\WorkermanServerBundle\Command\:
    resource: '../../Command/'
  Tourze\WorkermanServerBundle\HTTP\:
    resource: '../../HTTP/'

  # MIME detector service
  workerman-server.mime-detector:
    class: League\MimeTypeDetection\FinfoMimeTypeDetector
